# Generated by Django 5.0.9 on 2024-10-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
    ]
