# Generated by Django 5.0.9 on 2024-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
